### ISSUE TITLE
Error en app tras deploy ya hecho

### ISSUE THREAD

**Issue by Nicksoliss** [IIC2513-2021-1/projects#37]
Holas, tenemos una consulta. Hicimos un deploy exitoso en Heroku pero al momento de entrar a la app nos manda error y ya no sabemos por qué. Cualquier ayuda se agradecería. El heroku logs --tail nos entrega esto:

heroku logs --tail
 »   Warning: heroku update available from 7.47.3 to 7.53.0.
2021-05-04T02:25:52.584100+00:00 app[web.1]: at Object.<anonymous> (/app/src/config/database.js:1:1)
2021-05-04T02:25:52.584100+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:999:30)
2021-05-04T02:25:52.584100+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2021-05-04T02:25:52.584101+00:00 app[web.1]: at Module.load (internal/modules/cjs/loader.js:863:32)
2021-05-04T02:25:52.584101+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2021-05-04T02:25:52.584101+00:00 app[web.1]: at Module.require (internal/modules/cjs/loader.js:887:19) {
2021-05-04T02:25:52.584102+00:00 app[web.1]: code: 'MODULE_NOT_FOUND',
2021-05-04T02:25:52.584102+00:00 app[web.1]: requireStack: [
2021-05-04T02:25:52.584102+00:00 app[web.1]: '/app/src/config/database.js',
2021-05-04T02:25:52.584103+00:00 app[web.1]: '/app/src/models/index.js',
2021-05-04T02:25:52.584103+00:00 app[web.1]: '/app/src/app.js',
2021-05-04T02:25:52.584103+00:00 app[web.1]: '/app/index.js'
2021-05-04T02:25:52.584104+00:00 app[web.1]: ]
2021-05-04T02:25:52.584104+00:00 app[web.1]: }
2021-05-04T02:25:52.632848+00:00 app[web.1]: error Command failed with exit code 1.
2021-05-04T02:25:52.633082+00:00 app[web.1]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2021-05-04T02:25:52.746128+00:00 heroku[web.1]: Process exited with status 1
2021-05-04T02:25:52.819413+00:00 heroku[web.1]: State changed from starting to crashed
2021-05-04T02:26:28.021200+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=entrega-11-iic2513.herokuapp.com request_id=5de1c44d-f01a-49e7-8f69-c6a12816fb6f fwd="190.163.6.103" dyno= connect= service= status=503 bytes= protocol=https
2021-05-04T02:26:28.768761+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=entrega-11-iic2513.herokuapp.com request_id=64c7dfc0-0ce6-41e8-8e69-69ef74df1882 fwd="190.163.6.103" dyno= connect= service= status=503 bytes= protocol=https
2021-05-04T02:31:32.888464+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=entrega-11-iic2513.herokuapp.com request_id=d4bbb5b6-fc44-4a25-bf50-07d17ff4b15e fwd="190.163.6.103" dyno= connect= service= status=503 bytes= protocol=https
2021-05-04T02:31:33.360958+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=entrega-11-iic2513.herokuapp.com request_id=4d720cb9-2f5a-4204-829c-f7146b3ccd1c fwd="190.163.6.103" dyno= connect= service= status=503 bytes= protocol=https
2021-05-04T02:45:44.000000+00:00 app[api]: Build started by user nisolis@uc.cl
2021-05-04T02:46:45.580360+00:00 app[api]: Deploy cdb95c8f by user nisolis@uc.cl
2021-05-04T02:46:45.580360+00:00 app[api]: Release v7 created by user nisolis@uc.cl
2021-05-04T02:46:45.801529+00:00 heroku[web.1]: State changed from crashed to starting
2021-05-04T02:46:48.726985+00:00 heroku[web.1]: Starting process with command `yarn start`
2021-05-04T02:46:50.973742+00:00 app[web.1]: yarn run v1.22.10
2021-05-04T02:46:51.016288+00:00 app[web.1]: $ node index.js
2021-05-04T02:46:51.528591+00:00 app[web.1]: internal/modules/cjs/loader.js:818
2021-05-04T02:46:51.528609+00:00 app[web.1]: throw err;
2021-05-04T02:46:51.528610+00:00 app[web.1]: ^
2021-05-04T02:46:51.528610+00:00 app[web.1]:
2021-05-04T02:46:51.528611+00:00 app[web.1]: Error: Cannot find module 'dotenv'
2021-05-04T02:46:51.528611+00:00 app[web.1]: Require stack:
2021-05-04T02:46:51.528612+00:00 app[web.1]: - /app/src/config/database.js
2021-05-04T02:46:51.528613+00:00 app[web.1]: - /app/src/models/index.js
2021-05-04T02:46:51.528613+00:00 app[web.1]: - /app/src/app.js
2021-05-04T02:46:51.528613+00:00 app[web.1]: - /app/index.js
2021-05-04T02:46:51.528615+00:00 app[web.1]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
2021-05-04T02:46:51.528615+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:667:27)
2021-05-04T02:46:51.528616+00:00 app[web.1]: at Module.require (internal/modules/cjs/loader.js:887:19)
2021-05-04T02:46:51.528616+00:00 app[web.1]: at require (internal/modules/cjs/helpers.js:74:18)
2021-05-04T02:46:51.528617+00:00 app[web.1]: at Object.<anonymous> (/app/src/config/database.js:1:1)
2021-05-04T02:46:51.528617+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:999:30)
2021-05-04T02:46:51.528618+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2021-05-04T02:46:51.528618+00:00 app[web.1]: at Module.load (internal/modules/cjs/loader.js:863:32)
2021-05-04T02:46:51.528618+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2021-05-04T02:46:51.528619+00:00 app[web.1]: at Module.require (internal/modules/cjs/loader.js:887:19) {
2021-05-04T02:46:51.528619+00:00 app[web.1]: code: 'MODULE_NOT_FOUND',
2021-05-04T02:46:51.528620+00:00 app[web.1]: requireStack: [
2021-05-04T02:46:51.528620+00:00 app[web.1]: '/app/src/config/database.js',
2021-05-04T02:46:51.528620+00:00 app[web.1]: '/app/src/models/index.js',
2021-05-04T02:46:51.528621+00:00 app[web.1]: '/app/src/app.js',
2021-05-04T02:46:51.528621+00:00 app[web.1]: '/app/index.js'
2021-05-04T02:46:51.528621+00:00 app[web.1]: ]
2021-05-04T02:46:51.528622+00:00 app[web.1]: }
2021-05-04T02:46:51.549982+00:00 app[web.1]: error Command failed with exit code 1.
2021-05-04T02:46:51.550186+00:00 app[web.1]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2021-05-04T02:46:51.608500+00:00 heroku[web.1]: Process exited with status 1
2021-05-04T02:46:51.673130+00:00 heroku[web.1]: State changed from starting to crashed
2021-05-04T02:46:51.683568+00:00 heroku[web.1]: State changed from crashed to starting
2021-05-04T02:46:52.000000+00:00 app[api]: Build succeeded
2021-05-04T02:46:55.037145+00:00 heroku[web.1]: Starting process with command `yarn start`
2021-05-04T02:46:57.646471+00:00 app[web.1]: yarn run v1.22.10
2021-05-04T02:46:57.691496+00:00 app[web.1]: $ node index.js
2021-05-04T02:46:58.235039+00:00 app[web.1]: internal/modules/cjs/loader.js:818
2021-05-04T02:46:58.235091+00:00 app[web.1]: throw err;
2021-05-04T02:46:58.235091+00:00 app[web.1]: ^
2021-05-04T02:46:58.235092+00:00 app[web.1]:
2021-05-04T02:46:58.235093+00:00 app[web.1]: Error: Cannot find module 'dotenv'
2021-05-04T02:46:58.235094+00:00 app[web.1]: Require stack:
2021-05-04T02:46:58.235095+00:00 app[web.1]: - /app/src/config/database.js
2021-05-04T02:46:58.235095+00:00 app[web.1]: - /app/src/models/index.js
2021-05-04T02:46:58.235095+00:00 app[web.1]: - /app/src/app.js
2021-05-04T02:46:58.235096+00:00 app[web.1]: - /app/index.js
2021-05-04T02:46:58.235097+00:00 app[web.1]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
2021-05-04T02:46:58.235097+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:667:27)
2021-05-04T02:46:58.235098+00:00 app[web.1]: at Module.require (internal/modules/cjs/loader.js:887:19)
2021-05-04T02:46:58.235099+00:00 app[web.1]: at require (internal/modules/cjs/helpers.js:74:18)
2021-05-04T02:46:58.235099+00:00 app[web.1]: at Object.<anonymous> (/app/src/config/database.js:1:1)
2021-05-04T02:46:58.235100+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:999:30)
2021-05-04T02:46:58.235100+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2021-05-04T02:46:58.235100+00:00 app[web.1]: at Module.load (internal/modules/cjs/loader.js:863:32)
2021-05-04T02:46:58.235101+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2021-05-04T02:46:58.235101+00:00 app[web.1]: at Module.require (internal/modules/cjs/loader.js:887:19) {
2021-05-04T02:46:58.235101+00:00 app[web.1]: code: 'MODULE_NOT_FOUND',
2021-05-04T02:46:58.235102+00:00 app[web.1]: requireStack: [
2021-05-04T02:46:58.235102+00:00 app[web.1]: '/app/src/config/database.js',
2021-05-04T02:46:58.235102+00:00 app[web.1]: '/app/src/models/index.js',
2021-05-04T02:46:58.235103+00:00 app[web.1]: '/app/src/app.js',
2021-05-04T02:46:58.235103+00:00 app[web.1]: '/app/index.js'
2021-05-04T02:46:58.235103+00:00 app[web.1]: ]
2021-05-04T02:46:58.235104+00:00 app[web.1]: }
2021-05-04T02:46:58.254866+00:00 app[web.1]: error Command failed with exit code 1.
2021-05-04T02:46:58.255067+00:00 app[web.1]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2021-05-04T02:46:58.324884+00:00 heroku[web.1]: Process exited with status 1
2021-05-04T02:46:58.421202+00:00 heroku[web.1]: State changed from starting to crashed
2021-05-04T02:47:05.876276+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=entrega-11-iic2513.herokuapp.com request_id=e93c07a9-1614-4efa-acd0-313b1d3766b9 fwd="190.163.6.103" dyno= connect= service= status=503 bytes= protocol=https
2021-05-04T02:47:06.435971+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=entrega-11-iic2513.herokuapp.com request_id=9181cac5-88c2-497e-8110-3d8d394ab5f6 fwd="190.163.6.103" dyno= connect= service= status=503 bytes= protocol=https

**Comment by dhvasquez** [comment]
Hola, primero que todo ¿Pudieron resolverlo?, de no ser así, se ve que es un problema donde heroku no esta tomando como instalado el paquete dotenv, ¿De casualidad esta es paquete en dependencias de desarrollador? (Para revisar vayan a su package.json y revisen si el paquete ```dotenv``` se encuentra bajo ```devDependencies```).

**Comment by Nicksoliss** [comment]
Hola! Pudimos resolverlo al último minuto, debía dejarlo en Dependencies y no en devDependencies. Gracias igual!
